### ISSUE TITLE
GSM RingOut when Alarm

### ISSUE THREAD

**Issue by Tenshinur** [dgray10/SecPi#105]
I want to use the Raspberry Pi 3 as a home alarm.
- 10 reed switches (magnetic sensors)
- 2 motion sensors
- The gas sensor (propane)
- 2 smoke detectors
- 2 water sensors
- SMS notification when all
- Call to the number when triggering magnetic sensors or motion
When calling I / O through a microphone / speaker

As far as the functionality of your project is seen, all this through it is feasible, except for the call function. Can I find out whether it will be added or where can I find the ready-made code for this?

Sorry but my english, this is g-translate ;)

**Comment by MartinLiebl** [comment]
Hey!
My thoughts on that:

- You'll probably need to figure out how to get all of this sensors on the Pi since you'll need a lot of GPIO pins. You can use multiple Pis though.
- We don't have implementations for reed switches, gas sensors, smoke detectors and water sensors, although it should be easy to add them. We wrote about adding your own sensory here: https://github.com/SecPi/SecPi/wiki/Sensors.
- The calling and I/O through microphone/speaker is currently not on the roadmap and I don't think it will happen anytime soon. So unfortunately you would be on your own with this.

Sorry for the late reply!
Cheers,
Martin
